[book]
authors = ["Kk Shinkai"]
language = "zh"
multilingual = false
src = "src"
title = "What I Wish I Knew"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
smart-punctuation = true
no-section-label = true

[output.html.fold]
enable = true
